import type { Product, ProductOption, ProductVariant } from "./schema";
import { CSVMeta } from "./schema";

function csvEscape(cell: string): string {
  if (!cell) return "";
  if (cell.includes(",") || cell.includes('"') || cell.includes("\n")) {
    return `"${cell.replace(/"/g, '""')}"`;
  }
  return cell;
}

function csvRow(values: (string | number | null | undefined)[]): string {
  return values.map(v => csvEscape(v != null ? String(v) : "")).join(",");
}

function serializeVariant(v: ProductVariant, _depth: number): string {
  const parts = [
    v.name,
    v.price,
    v.costPrice ?? 0,
    v.minQty ?? 0,
    v.description ?? "",
    v.imageUrl ?? "",
  ];

  const base = parts.join(",");

  if (v.nestedOptions && v.nestedOptions.length > 0) {
    const nestedStr = v.nestedOptions
      .map((o: ProductOption) => serializeNestedOption(o))
      .join(" ");
    return base + " " + nestedStr;
  }

  return base;
}

function serializeNestedOption(o: ProductOption): string {
  const rangeStr = `"[${o.range[0]},${o.range[1]}]"`;

  const variantsStr = o.variants
    .map((v: ProductVariant) => serializeVariant(v, 1))
    .join(" ; ");

  return `{ ${o.name},${o.type === "single" ? "single" : "multiple"},${o.enableRange ? "yes" : "no"},${rangeStr},${o.required ? "yes" : "no"},${o.view} ( ${variantsStr} ) }`;
}

export function generateOptionColumns(
  products: Product[]
): { headers: string[]; maxOpts: number } {
  let maxOpts = 0;
  for (const p of products) {
    const activeOpts = (p.options || []).filter(
      (o) => o.variants && o.variants.length > 0
    );
    if (activeOpts.length > maxOpts) {
      maxOpts = activeOpts.length;
    }
  }
  // Always emit at least OPTION1 columns even if empty (for CSV structure)
  if (maxOpts === 0) maxOpts = 1;

  const headers: string[] = [];
  for (let i = 1; i <= maxOpts; i++) {
    for (const name of CSVMeta.OPTION_HEADER_NAMES) {
      headers.push(`OPTION${i}.${name}`);
    }
  }

  return { headers, maxOpts };
}

export function generateCSV(products: Product[]): string {
  const { headers: optionHeaders, maxOpts } = generateOptionColumns(products);

  const fullHeaders = [...CSVMeta.HEADERS, ...optionHeaders];
  let csv = csvRow(fullHeaders) + "\r\n";

  for (const p of products) {
    const baseRow: (string | number | null | undefined)[] = [
      "", // ID - auto-generated by Hyperzod
      p.name,
      p.description ?? "",
      p.sku ?? "",
      p.priceCompare != null ? p.priceCompare : "",
      p.minQty != null && p.maxQty != null
        ? `${p.minQty},${p.maxQty}`
        : "",
      p.sellingPrice > 0 ? p.sellingPrice : "",
      p.costPrice != null ? p.costPrice : 0,
      p.taxPercent != null ? p.taxPercent : "",
      p.status.toUpperCase(),
      p.inventory != null ? p.inventory : "",
      (p.labels ?? []).join(","),
      p.category,
      (p.tags ?? []).join(","),
      p.imageUrl ?? "",
    ];

    const options = (p.options ?? []).filter(
      (o) => o.variants && o.variants.length > 0
    );
    for (let i = 0; i < maxOpts; i++) {
      if (i < options.length) {
        const opt = options[i];
        const rangeStr = `${opt.range[0]},${opt.range[1]}`;
        const variantsStr = opt.variants
          .map((v: ProductVariant) => serializeVariant(v, 0))
          .join(" ; ");

        baseRow.push(
          opt.name,
          opt.type.toUpperCase(),
          opt.enableRange ? "YES" : "NO",
          rangeStr,
          opt.required ? "YES" : "NO",
          opt.view.toUpperCase(),
          variantsStr
        );
      } else {
        for (let j = 0; j < 7; j++) baseRow.push("");
      }
    }

    csv += csvRow(baseRow) + "\r\n";
  }

  return csv;
}
